### ISSUE TITLE
An option to preserve port numbers in metrics

### ISSUE THREAD

**Issue by innogrey** [automixer/gobi#2]
Is there any way to keep port numbers in metrics instead of converting them to service names (which seems to happen by default)? This would allow aggregation of flows received from exporters that doesn't support bidirectional flows, as well as gathering information based on custom port numbers.

**Comment by automixer** [comment]
Your request is interesting. I added three new configuration keys in the "Producer" section of the config file to disable the conversion from number to name of ports, protocols and etherType fields. Look at the [CONFIG-GUIDE.md](https://github.com/automixer/gobi/blob/main/doc/CONFIG-GUIDE.md) file for better explanation.
The only drawback thai I see is that with these options enabled, the db cardinality will increase a lot.

**Comment by innogrey** [comment]
Thank you very much for adding the functionality so promptly. I'm in the middle of testing. Of course cardinality increases, but so far it's within acceptable limits. It seems that I'll be able to replace resource-intensive elk stack with the goflow->gobi->prometheus->grafana flow. It looks promising :)

And one thing that crossed my mind, somehow related. Would it be reasonable to group inbound and outbound flow records into bidirectional flows? In fact, I'm not sure if it is even possible. In theory, matching source and destination addresses and port numbers should be feasible, reducing the number of returned metrics by half. I believe some netflow exporters do this, but rather not the open source ones. Again, however, I'm not exactly sure, would that make sense on the gobi side, or should aggregation like this be left for the prometheus queries.

**Comment by automixer** [comment]
Hi @innogrey, apologies for the delay. 
It's hard to correlate flows without falling in to a specific use case. Could you please describe me your needs more precisely? If we can find a feature that can be useful to anyone, I'll be happy to implement it. 
Have you looked over the two examples? May be they aren't close to your use case but they contain several tricks to correlate flows in a bidirectional way, via prom queries.
